./" This is the manpage of hangman
.TH hangman 6 "2017-03-18" "V1.0" "hangman man page"

.SH NAME
hangman

.SH DESCRIPTION
Hangman game made in bash. Try to guess the correct word before you run out of trys! Become a legend and improve your word knowledge!

.SH OPTIONS
.IP -w
Fill in a word of your choice and let someone else guess it! -> hangman -w <WORD>
.IP -d
Load in a dictionary of words to guess. You can use Woordenlijst.txt to try it out! -> hangman -d <PATH TO FILE>
.IP -l
Choose the language of your hangman game! -> hangman -l <EN OR NL>

.SH AUTHORS
Dennis Tijbosch & Shaun van Beurden